### ISSUE TITLE
データを定期的に更新したい

### ISSUE THREAD

**Issue by ku-mok** [ku-mok/lilydle#3]
バックエンドを用意せずにやってるので適当にfirestoreでapi作るか、firebase functionでpull request生成するようにする

**Comment by ku-mok** [comment]
github actionsをcloud functionsからトリガーさせる

**Comment by fvh-P** [comment]
ワークフローの定時実行ならGithub Actions単体でもできますよ～
https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#schedule
